### ISSUE TITLE
Support for task items

### ISSUE THREAD

**Issue by masonlr** [lloyd094/Typora-Law-School#4]
Great work with the css theme. Is the checkbox formatting intentional? (The boxes cross over each other, etc.)

![image](https://user-images.githubusercontent.com/5828176/53149067-87c11f00-35a4-11e9-976d-79dbf18afbcf.png)

Would you support making this more like, say, the vue theme below:

![image](https://user-images.githubusercontent.com/5828176/53149054-80017a80-35a4-11e9-9b4a-4bcfc026d3e4.png)

**Comment by masonlr** [comment]
Okay. This can be achieved by commenting out the `.task-list-item` and `.md-task-list-item` entries. Good enough for me for local work, no need to edit your template  : )

```css

.md-task-list-item>input {
    margin-left: -1.3em;
    margin-top: 0.28em;
}

/* .task-list-item input:before {
    content: '\221A';
    display: inline-block;
    width: 1.25rem;
    height: 1.6rem;
    vertical-align: middle;
    text-align: center;
    color: #bbb;
    background-color: inherit;
}

.task-list-item input:checked:before,
.task-list-item input[checked]:before{
    color: inherit;
}

.md-task-list-item > input {
    top: auto;
    margin-left: -1.1em;
    font-size: 1.3em;
    margin-top: 0px;
    -webkit-appearance: none;
}

.md-task-list-item input:before {
    content: '\2610';
    display: inline-block;
    width: 1.25rem;
    height: 1.6rem;
    vertical-align: middle;
    text-align: center;
    color: #bbb;
    background-color: inherit;
}

.md-task-list-item input:checked:before,
.md-task-list-item input[checked]:before{
    color: inherit;
    content: '\2611';
}

.task-list-item {
    padding-left: 1.2em;
} */
```
